#!/bin/bash -xe
DEST=/opt/plancton/git
BRANCH=master
cd /
[[ $(whoami) == plancton ]]
[[ -d $DEST/.git ]] || git clone -b $BRANCH https://github.com/mconcas/plancton $DEST
cd $DEST
git remote update -p
git clean -f -d
git clean -fX -d
git checkout $BRANCH
git reset --hard origin/$BRANCH
export PATH=$PATH:$DEST/bin
export PYTHONPATH=$PYTHONPATH:$DEST/pylibs
planctonctl start
